spring:
  profiles:
  #选择环境
    active: prd
server:
  port: 8088
# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-argugments: true
  params: count=countSql
#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.dabin.pojo
  mapperLocations: classpath:mappers/**/*.xml
# 打印sql
logging:
  level:
    com.dabin: debug
    com.dabin.dao : debug

user:
    username: dabin
    password: 123456
